alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

server:
  persistentVolume:
    enabled: false
  retention: 6h
  global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
