alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: true
  metricLabelsAllowlist:
    - pods=[app.kubernetes.io/name,app.kubernetes.io/part-of,app.kubernetes.io/environment,vaipex.io/owner,vaipex.io/cost-center,vaipex.io/capacity-profile]
    - deployments=[app.kubernetes.io/name,app.kubernetes.io/part-of,app.kubernetes.io/environment,vaipex.io/owner,vaipex.io/cost-center,vaipex.io/capacity-profile]

prometheus-node-exporter:
  enabled: true

server:
  persistentVolume:
    enabled: false
  retention: 6h
  global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

serverFiles:
  recording_rules.yml:
    groups:
      - name: vaipex-cost-capacity
        interval: 30s
        rules:
          - record: vaipex_workload_cpu_request_cores
            expr: |
              sum by (namespace, pod) (
                kube_pod_container_resource_requests{
                  namespace="vaipex-cost-demo",
                  resource="cpu",
                  unit="core"
                }
              )
          - record: vaipex_workload_cpu_usage_cores
            expr: |
              sum by (namespace, pod) (
                rate(container_cpu_usage_seconds_total{
                  namespace="vaipex-cost-demo",
                  container="workload"
                }[5m])
              )
          - record: vaipex_workload_cpu_request_utilization_ratio
            expr: |
              vaipex_workload_cpu_usage_cores
              /
              vaipex_workload_cpu_request_cores
          - record: vaipex_workload_memory_request_bytes
            expr: |
              sum by (namespace, pod) (
                kube_pod_container_resource_requests{
                  namespace="vaipex-cost-demo",
                  resource="memory",
                  unit="byte"
                }
              )
          - record: vaipex_workload_memory_usage_bytes
            expr: |
              sum by (namespace, pod) (
                container_memory_working_set_bytes{
                  namespace="vaipex-cost-demo",
                  container="workload"
                }
              )
          - record: vaipex_workload_memory_request_utilization_ratio
            expr: |
              vaipex_workload_memory_usage_bytes
              /
              vaipex_workload_memory_request_bytes
